server:
  port: 8080

spring:
  redis:
    #    Redis服务端主机地址
#    host: 192.168.2.128
    host: 139.196.88.44
    #    服务端端口号
    port: 6379
    #    服务端连接密码
    password: 12345
    #    连接超时时间(ms)
    timeout: 2000
    lettuce:
      pool:
        #        最大连接数(负值为无限制)
        max-active: 8
        #        最大空闲连接
        max-idle: 8
        #        最小空闲连接
        min-idle: 0
        #        最大阻塞等待时间(负值为无限制)
        max-wait: 1000
  mvc:
    view:
      prefix: .html